/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminKingRouteRouteImport } from './routes/admin.king.route'
import { Route as AdminKingIndexRouteImport } from './routes/admin.king.index'
import { Route as AdminKingTdsRouteImport } from './routes/admin.king.tds'
import { Route as AdminKingQrScansRouteImport } from './routes/admin.king.qr-scans'
import { Route as AdminKingQrRouteImport } from './routes/admin.king.qr'
import { Route as AdminKingProductsRouteImport } from './routes/admin.king.products'
import { Route as AdminKingOrdersRouteImport } from './routes/admin.king.orders'
import { Route as AdminKingLoginRouteImport } from './routes/admin.king.login'
import { Route as AdminKingCustomersRouteImport } from './routes/admin.king.customers'
import { Route as AdminKingCashbackRouteImport } from './routes/admin.king.cashback'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKingRouteRoute = AdminKingRouteRouteImport.update({
  id: '/admin/king',
  path: '/admin/king',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKingIndexRoute = AdminKingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminKingRouteRoute,
} as any)
const AdminKingTdsRoute = AdminKingTdsRouteImport.update({
  id: '/tds',
  path: '/tds',
  getParentRoute: () => AdminKingRouteRoute,
} as any)
const AdminKingQrScansRoute = AdminKingQrScansRouteImport.update({
  id: '/qr-scans',
  path: '/qr-scans',
  getParentRoute: () => AdminKingRouteRoute,
} as any)
const AdminKingQrRoute = AdminKingQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AdminKingRouteRoute,
} as any)
const AdminKingProductsRoute = AdminKingProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminKingRouteRoute,
} as any)
const AdminKingOrdersRoute = AdminKingOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminKingRouteRoute,
} as any)
const AdminKingLoginRoute = AdminKingLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminKingRouteRoute,
} as any)
const AdminKingCustomersRoute = AdminKingCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminKingRouteRoute,
} as any)
const AdminKingCashbackRoute = AdminKingCashbackRouteImport.update({
  id: '/cashback',
  path: '/cashback',
  getParentRoute: () => AdminKingRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/report': typeof ReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/king': typeof AdminKingRouteRouteWithChildren
  '/admin/king/cashback': typeof AdminKingCashbackRoute
  '/admin/king/customers': typeof AdminKingCustomersRoute
  '/admin/king/login': typeof AdminKingLoginRoute
  '/admin/king/orders': typeof AdminKingOrdersRoute
  '/admin/king/products': typeof AdminKingProductsRoute
  '/admin/king/qr': typeof AdminKingQrRoute
  '/admin/king/qr-scans': typeof AdminKingQrScansRoute
  '/admin/king/tds': typeof AdminKingTdsRoute
  '/admin/king/': typeof AdminKingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/report': typeof ReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/king/cashback': typeof AdminKingCashbackRoute
  '/admin/king/customers': typeof AdminKingCustomersRoute
  '/admin/king/login': typeof AdminKingLoginRoute
  '/admin/king/orders': typeof AdminKingOrdersRoute
  '/admin/king/products': typeof AdminKingProductsRoute
  '/admin/king/qr': typeof AdminKingQrRoute
  '/admin/king/qr-scans': typeof AdminKingQrScansRoute
  '/admin/king/tds': typeof AdminKingTdsRoute
  '/admin/king': typeof AdminKingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/report': typeof ReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/king': typeof AdminKingRouteRouteWithChildren
  '/admin/king/cashback': typeof AdminKingCashbackRoute
  '/admin/king/customers': typeof AdminKingCustomersRoute
  '/admin/king/login': typeof AdminKingLoginRoute
  '/admin/king/orders': typeof AdminKingOrdersRoute
  '/admin/king/products': typeof AdminKingProductsRoute
  '/admin/king/qr': typeof AdminKingQrRoute
  '/admin/king/qr-scans': typeof AdminKingQrScansRoute
  '/admin/king/tds': typeof AdminKingTdsRoute
  '/admin/king/': typeof AdminKingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/products'
    | '/report'
    | '/sitemap.xml'
    | '/admin/king'
    | '/admin/king/cashback'
    | '/admin/king/customers'
    | '/admin/king/login'
    | '/admin/king/orders'
    | '/admin/king/products'
    | '/admin/king/qr'
    | '/admin/king/qr-scans'
    | '/admin/king/tds'
    | '/admin/king/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/products'
    | '/report'
    | '/sitemap.xml'
    | '/admin/king/cashback'
    | '/admin/king/customers'
    | '/admin/king/login'
    | '/admin/king/orders'
    | '/admin/king/products'
    | '/admin/king/qr'
    | '/admin/king/qr-scans'
    | '/admin/king/tds'
    | '/admin/king'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/products'
    | '/report'
    | '/sitemap.xml'
    | '/admin/king'
    | '/admin/king/cashback'
    | '/admin/king/customers'
    | '/admin/king/login'
    | '/admin/king/orders'
    | '/admin/king/products'
    | '/admin/king/qr'
    | '/admin/king/qr-scans'
    | '/admin/king/tds'
    | '/admin/king/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRoute
  ReportRoute: typeof ReportRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminKingRouteRoute: typeof AdminKingRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/king': {
      id: '/admin/king'
      path: '/admin/king'
      fullPath: '/admin/king'
      preLoaderRoute: typeof AdminKingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/king/': {
      id: '/admin/king/'
      path: '/'
      fullPath: '/admin/king/'
      preLoaderRoute: typeof AdminKingIndexRouteImport
      parentRoute: typeof AdminKingRouteRoute
    }
    '/admin/king/tds': {
      id: '/admin/king/tds'
      path: '/tds'
      fullPath: '/admin/king/tds'
      preLoaderRoute: typeof AdminKingTdsRouteImport
      parentRoute: typeof AdminKingRouteRoute
    }
    '/admin/king/qr-scans': {
      id: '/admin/king/qr-scans'
      path: '/qr-scans'
      fullPath: '/admin/king/qr-scans'
      preLoaderRoute: typeof AdminKingQrScansRouteImport
      parentRoute: typeof AdminKingRouteRoute
    }
    '/admin/king/qr': {
      id: '/admin/king/qr'
      path: '/qr'
      fullPath: '/admin/king/qr'
      preLoaderRoute: typeof AdminKingQrRouteImport
      parentRoute: typeof AdminKingRouteRoute
    }
    '/admin/king/products': {
      id: '/admin/king/products'
      path: '/products'
      fullPath: '/admin/king/products'
      preLoaderRoute: typeof AdminKingProductsRouteImport
      parentRoute: typeof AdminKingRouteRoute
    }
    '/admin/king/orders': {
      id: '/admin/king/orders'
      path: '/orders'
      fullPath: '/admin/king/orders'
      preLoaderRoute: typeof AdminKingOrdersRouteImport
      parentRoute: typeof AdminKingRouteRoute
    }
    '/admin/king/login': {
      id: '/admin/king/login'
      path: '/login'
      fullPath: '/admin/king/login'
      preLoaderRoute: typeof AdminKingLoginRouteImport
      parentRoute: typeof AdminKingRouteRoute
    }
    '/admin/king/customers': {
      id: '/admin/king/customers'
      path: '/customers'
      fullPath: '/admin/king/customers'
      preLoaderRoute: typeof AdminKingCustomersRouteImport
      parentRoute: typeof AdminKingRouteRoute
    }
    '/admin/king/cashback': {
      id: '/admin/king/cashback'
      path: '/cashback'
      fullPath: '/admin/king/cashback'
      preLoaderRoute: typeof AdminKingCashbackRouteImport
      parentRoute: typeof AdminKingRouteRoute
    }
  }
}

interface AdminKingRouteRouteChildren {
  AdminKingCashbackRoute: typeof AdminKingCashbackRoute
  AdminKingCustomersRoute: typeof AdminKingCustomersRoute
  AdminKingLoginRoute: typeof AdminKingLoginRoute
  AdminKingOrdersRoute: typeof AdminKingOrdersRoute
  AdminKingProductsRoute: typeof AdminKingProductsRoute
  AdminKingQrRoute: typeof AdminKingQrRoute
  AdminKingQrScansRoute: typeof AdminKingQrScansRoute
  AdminKingTdsRoute: typeof AdminKingTdsRoute
  AdminKingIndexRoute: typeof AdminKingIndexRoute
}

const AdminKingRouteRouteChildren: AdminKingRouteRouteChildren = {
  AdminKingCashbackRoute: AdminKingCashbackRoute,
  AdminKingCustomersRoute: AdminKingCustomersRoute,
  AdminKingLoginRoute: AdminKingLoginRoute,
  AdminKingOrdersRoute: AdminKingOrdersRoute,
  AdminKingProductsRoute: AdminKingProductsRoute,
  AdminKingQrRoute: AdminKingQrRoute,
  AdminKingQrScansRoute: AdminKingQrScansRoute,
  AdminKingTdsRoute: AdminKingTdsRoute,
  AdminKingIndexRoute: AdminKingIndexRoute,
}

const AdminKingRouteRouteWithChildren = AdminKingRouteRoute._addFileChildren(
  AdminKingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRoute,
  ReportRoute: ReportRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminKingRouteRoute: AdminKingRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
